[package]
name = "fxp_filenames"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
regex = "1.11.1"
log = "0.4"
thiserror = "2.0.11"

fxp_modes = {version = "0.4.0", path = "../fxp_modes"}
