mod audio_dir;
mod config;
mod duration;
mod fps;
mod literals;
mod log_config;
mod media_duration;
mod mp3;
mod multiple_opacities;
mod opacity;
mod pixel;
mod sampling;

pub use audio_dir::get_audio_dir;
pub use config::initialize_configuration;
pub use config::load_default_configuration;
pub use config::Config;
pub use duration::get_duration;
pub use fps::get_fps;
pub use log_config::initialize_logger;
pub use media_duration::media_duration;
pub use mp3::{get_audio_duration, get_audio_file};
pub use multiple_opacities::get_multiple_opacities;
pub use opacity::get_opacity;
pub use pixel::get_pixel_upper_limit;
pub use sampling::get_sampling_number;
