/// Environment variable key for the audio path.
pub const FXP_VIDEOCLIPPER_AUDIO: &str = "FXP_VIDEOCLIPPER_AUDIO";
pub const FXP_VIDEOCLIPPER_OPACITY: &str = "FXP_VIDEOCLIPPER_OPACITY";
pub const FXP_VIDEOCLIPPER_MULTIPLE_OPACITIES: &str = "FXP_VIDEOCLIPPER_MULTIPLE_OPACITIES";
pub const FXP_VIDEOCLIPPER_FPS: &str = "FXP_VIDEOCLIPPER_FPS";
pub const FXP_VIDEOCLIPPER_SAMPLING_NUMBER: &str = "FXP_VIDEOCLIPPER_SAMPLING_NUMBER";
pub const FXP_VIDEOCLIPPER_PIXEL_LIMIT: &str = "FXP_VIDEOCLIPPER_PIXEL_LIMIT";
