[package]
name = "clutter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
indicatif = "0.17.9"
log = "0.4"
anyhow = "1.0.95"
rand = "0.8.0"
ctrlc = "3.2"

filenames = { path = "../filenames"}
