[package]
name = "fxp_modes"
version = "0.4.1"
edition = "2021"
description = "All modes for fxp_videoclipper"
license = "MIT OR Apache-2.0"

[dependencies]

[lib]
name = "fxp_modes"
path = "src/lib.rs"
